---
name: Deploy Pre-Release Artifacts

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'README.md'
      - '.github/workflows/deploy-pre-release.yml'
  schedule:
    - cron: '0 12 * * *' # Run everyday at noon
  workflow_dispatch: # Allows manual triggering of the workflow

concurrency:
  group: deploy-pre-release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHON_VERSION: '3.10'
  OWNER: eclipse-volttron

jobs:
  deploy-pre-release:
    uses: eclipse-volttron/github-tooling/.github/workflows/deploy-pre-release.yml@main
    secrets:
      pypi-token: ${{ secrets.PYPI_TOKEN }}
